/**
 * Mirix Response Types
 * Converted from: mirix/schemas/mirix_response.py
 */

import { z } from 'zod';
import { MirixMessageUnionSchema, type MirixMessageUnion } from './mirix_message';
import { MessageStreamStatus } from './enums';

// -------------------------------
// Usage Statistics Schema
// -------------------------------

export const MirixUsageStatisticsSchema = z.object({
    messageType: z.literal('usage_statistics').default('usage_statistics'),
    completionTokens: z.number().default(0).describe('The number of tokens generated by the agent'),
    promptTokens: z.number().default(0).describe('The number of tokens in the prompt'),
    lastPromptTokens: z.number().default(0).describe('The number of tokens in the last prompt'),
    lastCompletionTokens: z.number().default(0).describe('The number of tokens in the last completion'),
    totalTokens: z.number().default(0).describe('The total number of tokens processed by the agent'),
    stepCount: z.number().default(0).describe('The number of steps taken by the agent'),
});

export type MirixUsageStatistics = z.infer<typeof MirixUsageStatisticsSchema>;

// -------------------------------
// Response Schema
// -------------------------------

/**
 * Response object from an agent interaction, consisting of the new messages
 * generated by the agent and usage statistics.
 */
export const MirixResponseSchema = z.object({
    messages: z.array(MirixMessageUnionSchema).describe('The messages returned by the agent'),
    usage: MirixUsageStatisticsSchema.describe('The usage statistics of the agent'),
});

export type MirixResponse = z.infer<typeof MirixResponseSchema>;

// -------------------------------
// Streaming Response Schema
// -------------------------------

/**
 * The streaming response is either [DONE], a MirixMessage, or MirixUsageStatistics
 */
export const MessageStreamStatusSchema = z.literal(MessageStreamStatus.DONE);

export const MirixStreamingResponseSchema = z.union([
    MirixMessageUnionSchema,
    MessageStreamStatusSchema,
    MirixUsageStatisticsSchema,
]);

export type MirixStreamingResponse = z.infer<typeof MirixStreamingResponseSchema>;

// -------------------------------
// Helper Functions
// -------------------------------

export function createMirixResponse(
    messages: MirixMessageUnion[],
    usage: Partial<MirixUsageStatistics> = {}
): MirixResponse {
    return {
        messages,
        usage: {
            messageType: 'usage_statistics',
            completionTokens: usage.completionTokens ?? 0,
            promptTokens: usage.promptTokens ?? 0,
            lastPromptTokens: usage.lastPromptTokens ?? 0,
            lastCompletionTokens: usage.lastCompletionTokens ?? 0,
            totalTokens: usage.totalTokens ?? 0,
            stepCount: usage.stepCount ?? 0,
        },
    };
}

export function createEmptyUsageStatistics(): MirixUsageStatistics {
    return {
        messageType: 'usage_statistics',
        completionTokens: 0,
        promptTokens: 0,
        lastPromptTokens: 0,
        lastCompletionTokens: 0,
        totalTokens: 0,
        stepCount: 0,
    };
}

/**
 * Aggregate multiple usage statistics into one
 */
export function aggregateUsageStatistics(
    usages: MirixUsageStatistics[]
): MirixUsageStatistics {
    return usages.reduce(
        (acc, usage) => ({
            messageType: 'usage_statistics',
            completionTokens: acc.completionTokens + usage.completionTokens,
            promptTokens: acc.promptTokens + usage.promptTokens,
            lastPromptTokens: usage.lastPromptTokens, // Use latest
            lastCompletionTokens: usage.lastCompletionTokens, // Use latest
            totalTokens: acc.totalTokens + usage.totalTokens,
            stepCount: acc.stepCount + usage.stepCount,
        }),
        createEmptyUsageStatistics()
    );
}
