/**
 * Mirix Message Content Types
 * Converted from: mirix/schemas/mirix_message_content.py
 */

import { z } from 'zod';

/**
 * Message content types
 */
export const MessageContentType = {
    TEXT: 'text',
    IMAGE_URL: 'image_url',
    FILE_URI: 'file_uri',
    GOOGLE_CLOUD_FILE_URI: 'google_cloud_file_uri',
    TOOL_CALL: 'tool_call',
    TOOL_RETURN: 'tool_return',
    REASONING: 'reasoning',
    REDACTED_REASONING: 'redacted_reasoning',
    OMITTED_REASONING: 'omitted_reasoning',
} as const;

export type MessageContentType = (typeof MessageContentType)[keyof typeof MessageContentType];

// -------------------------------
// User Content Types
// -------------------------------

export const TextContentSchema = z.object({
    type: z.literal(MessageContentType.TEXT),
    text: z.string().describe('The text content of the message'),
});

export type TextContent = z.infer<typeof TextContentSchema>;

export const ImageContentSchema = z.object({
    type: z.literal(MessageContentType.IMAGE_URL),
    imageId: z.string().describe('The id of the image in the database'),
    detail: z.string().nullable().optional().describe('The detail of the image'),
});

export type ImageContent = z.infer<typeof ImageContentSchema>;

export const FileContentSchema = z.object({
    type: z.literal(MessageContentType.FILE_URI),
    fileId: z.string().describe('The id of the file in the database'),
});

export type FileContent = z.infer<typeof FileContentSchema>;

export const CloudFileContentSchema = z.object({
    type: z.literal(MessageContentType.GOOGLE_CLOUD_FILE_URI),
    cloudFileUri: z.string().describe('The URI of the file in Google Cloud'),
});

export type CloudFileContent = z.infer<typeof CloudFileContentSchema>;

export const MirixUserMessageContentUnionSchema = z.discriminatedUnion('type', [
    TextContentSchema,
    ImageContentSchema,
    FileContentSchema,
    CloudFileContentSchema,
]);

export type MirixUserMessageContentUnion = z.infer<typeof MirixUserMessageContentUnionSchema>;

// -------------------------------
// Assistant Content Types
// -------------------------------

export const MirixAssistantMessageContentUnionSchema = z.discriminatedUnion('type', [
    TextContentSchema,
]);

export type MirixAssistantMessageContentUnion = z.infer<typeof MirixAssistantMessageContentUnionSchema>;

// -------------------------------
// Intermediate Step Content Types
// -------------------------------

export const ToolCallContentSchema = z.object({
    type: z.literal(MessageContentType.TOOL_CALL),
    id: z.string().describe('A unique identifier for this specific tool call instance'),
    name: z.string().describe('The name of the tool being called'),
    input: z.record(z.string(), z.unknown()).describe('The parameters being passed to the tool'),
});

export type ToolCallContent = z.infer<typeof ToolCallContentSchema>;

export const ToolReturnContentSchema = z.object({
    type: z.literal(MessageContentType.TOOL_RETURN),
    toolCallId: z.string().describe('References the ID of the ToolCallContent that initiated this tool call'),
    content: z.string().describe('The content returned by the tool execution'),
    isError: z.boolean().describe('Indicates whether the tool execution resulted in an error'),
});

export type ToolReturnContent = z.infer<typeof ToolReturnContentSchema>;

export const ReasoningContentSchema = z.object({
    type: z.literal(MessageContentType.REASONING),
    isNative: z.boolean().describe('Whether the reasoning content was generated by a reasoner model'),
    reasoning: z.string().describe('The intermediate reasoning or thought process content'),
    signature: z.string().nullable().optional().describe('A unique identifier for this reasoning step'),
});

export type ReasoningContent = z.infer<typeof ReasoningContentSchema>;

export const RedactedReasoningContentSchema = z.object({
    type: z.literal(MessageContentType.REDACTED_REASONING),
    data: z.string().describe('The redacted or filtered intermediate reasoning content'),
});

export type RedactedReasoningContent = z.infer<typeof RedactedReasoningContentSchema>;

export const OmittedReasoningContentSchema = z.object({
    type: z.literal(MessageContentType.OMITTED_REASONING),
    tokens: z.number().describe('The reasoning token count for intermediate reasoning content'),
});

export type OmittedReasoningContent = z.infer<typeof OmittedReasoningContentSchema>;

export const MirixMessageContentUnionSchema = z.discriminatedUnion('type', [
    TextContentSchema,
    ImageContentSchema,
    FileContentSchema,
    CloudFileContentSchema,
    ToolCallContentSchema,
    ToolReturnContentSchema,
    ReasoningContentSchema,
    RedactedReasoningContentSchema,
    OmittedReasoningContentSchema,
]);

export type MirixMessageContentUnion = z.infer<typeof MirixMessageContentUnionSchema>;

// -------------------------------
// Helper functions
// -------------------------------

export function createTextContent(text: string): TextContent {
    return { type: MessageContentType.TEXT, text };
}

export function createImageContent(imageId: string, detail?: string): ImageContent {
    return { type: MessageContentType.IMAGE_URL, imageId, detail };
}

export function createFileContent(fileId: string): FileContent {
    return { type: MessageContentType.FILE_URI, fileId };
}

export function createToolCallContent(id: string, name: string, input: Record<string, unknown>): ToolCallContent {
    return { type: MessageContentType.TOOL_CALL, id, name, input };
}

export function createToolReturnContent(toolCallId: string, content: string, isError: boolean): ToolReturnContent {
    return { type: MessageContentType.TOOL_RETURN, toolCallId, content, isError };
}
